---
title: "Day 9 Comp Session"
author: "Desik Somasundaram"
date: "8/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(kableExtra)
library(palmerpenguins)
library(janitor)
```


```{r}

starwars_dupes <- starwars %>% 
  clean_names()

starwars_dupes_names <- starwars %>% 
  get_dupes(hair_color)

```

##dplyer::across()

```{r}
sw_across <- starwars %>% 
  mutate(across(where(is.character), tolower))

sw_across
```
```{r}
starwars %>%
  group_by(homeworld) %>% 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))

```
### basic, common troubleshooting 

```{r}
starwars %>% 
  filter(homeworld == "Naboo")

```
```{r}
starwars %>% 
  separate(skin_color, into = c("col_1", "col_2"), sep = ",")
```

```{r}
ggplot(mtcars, aes(x = wt, y = mpg)) + geom_point()
```

```{r}
troubleshooting <- penguins %>% 
  mutate(across(where(is.numeric), as.character)) %>% 
  mutate(island = fct_relevel(island, c("Dream", "Biscoe", "Torgersen"))) %>%
  unite(island_yr, c(island, year), sep = "_") %>% 
  filter(species %in% c("Adelie", "Chinstrap")) %>% 
  relocate(year, .after = species) %>% 
  rename(penguin_spp = species)

```

```{r}
library(tidyverse)

df <-tribble ( ~name, ~height, ~hair_color,
               "Teddy", 2.2, "brown",
               "Khora", 3.1, "white",
               "Waffle", 1.0, "tan")
df %>% 
  filter(name == "Waffle")
```

